### GET request for user list
GET http://localhost:8090/api/v0/users
Authorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJleGVwdGFAcGdhLmNvbSIsInVpZCI6IjQwYTkzZWYzLTQzZDMtNGFiMC05OTU0LTQ1Nzk3YTBhNjEzYSIsInJvbGUiOiJtZW1iZXIiLCJleHAiOjE3MjU2MjUxNDl9.jXIutohPVpEoi16B0aKpPG98EY03t1MLO1yDz_ibYL8

### GET request for user list with attribs
GET http://localhost:8090/api/v0/users/role/member
Authorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJleGVwdGFAcGdhLmNvbSIsInVpZCI6IjQwYTkzZWYzLTQzZDMtNGFiMC05OTU0LTQ1Nzk3YTBhNjEzYSIsInJvbGUiOiJtZW1iZXIiLCJleHAiOjE3MjU2MjUxNDl9.jXIutohPVpEoi16B0aKpPG98EY03t1MLO1yDz_ibYL8

### GET request for single direct user
GET http://localhost:8090/api/v0/users/exepta
Authorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJleGVwdGFAcGdhLmNvbSIsInVpZCI6IjQwYTkzZWYzLTQzZDMtNGFiMC05OTU0LTQ1Nzk3YTBhNjEzYSIsInJvbGUiOiJtZW1iZXIiLCJleHAiOjE3MjU2MjUxNDl9.jXIutohPVpEoi16B0aKpPG98EY03t1MLO1yDz_ibYL8

### GET request for become user configuration list
GET http://localhost:8090/api/v0/conf/57283f8e-dbbb-4414-a942-853f962fc49b
Authorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJleGVwdGFAcGdhLmNvbSIsInVpZCI6IjQwYTkzZWYzLTQzZDMtNGFiMC05OTU0LTQ1Nzk3YTBhNjEzYSIsInJvbGUiOiJtZW1iZXIiLCJleHAiOjE3MjU2MjUxNDl9.jXIutohPVpEoi16B0aKpPG98EY03t1MLO1yDz_ibYL8

### POST auth register new user (Create the dummy for the login tests)
POST http://localhost:8090/api/v0/auth/register
Content-Type: application/json

{
  "username": "exepta",
  "email": "exepta@pga.com",
  "password": "123456",
  "birthday": "21/12/1996",
  "avatar_file": "base64:decoded",
  "banner_file": "base64:decoded",
  "configurations": "accent_color=#ff00a2"
}

### POST auth user login (Successfully)
POST http://localhost:8090/api/v0/auth/login
Content-Type: application/json

{
  "username": "exepta@pga.com",
  "password": "123456"
}

### POST auth user login (Failed)
POST http://localhost:8090/api/v0/auth/login
Content-Type: application/json

{
  "username": "exepta@pga.com",
  "password": "1234567"
}

### GET request for single direct user
GET http://localhost:8090/api/v0/auth/session_check
