### GET request for user list
GET http://localhost:8090/api/v0/users
Authorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJleGVwdGFAcGdhLmNvbSIsImV4cCI6MTcyNTI5MTU4M30.hOw_gBLocXByvYOUMHtv5x0-WO0VfxoKLPADnFA8JXc

### GET request for user list with attribs
GET http://localhost:8090/api/v0/users/role/member

### GET request for single direct user
GET http://localhost:8090/api/v0/users/exepta

### POST auth register new user (Create the dummy for the login tests)
POST http://localhost:8090/api/v0/auth/register
Content-Type: application/json

{
  "username": "exepta",
  "email": "exepta@pga.com",
  "password": "123456"
}

### POST auth user login (Successfully)
POST http://localhost:8090/api/v0/auth/login
Content-Type: application/json

{
  "username": "exepta@pga.com",
  "password": "123456"
}

### POST auth user login (Failed)
POST http://localhost:8090/api/v0/auth/login
Content-Type: application/json

{
  "username": "exepta@pga.com",
  "password": "1234567"
}

